<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreCommentRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'user_id' => 'required',
            'post_id' => 'required',
            'body' => 'required'
        ];
    }

    public function messages(): array
    {
        return [
            'user_id' => "User id si berilmagan",
            'post_id' => "Post id si berilmagan",
            'body' => "comment yozilmagan",
        ]; // TODO: Change the autogenerated stub
    }
}
